# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 20:52
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('registro_aluno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('nome_abreviado', models.CharField(max_length=40)),
                ('dtnascimento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('identidade', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('endereco', models.CharField(max_length=140)),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=3)),
                ('cep', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.ImageField(blank=True, default='alunos/sem_foto.png', null=True, upload_to='alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('turno', models.CharField(max_length=30)),
                ('turma', models.CharField(max_length=30)),
                ('disciplina', models.CharField(max_length=50)),
                ('notas1', models.CharField(max_length=10)),
                ('notas2', models.CharField(max_length=10)),
                ('notas3', models.CharField(max_length=10)),
                ('notas4', models.CharField(max_length=10)),
                ('media', models.CharField(max_length=10)),
                ('recuperacao', models.CharField(max_length=10)),
                ('faltas1', models.CharField(max_length=4)),
                ('faltas2', models.CharField(max_length=4)),
                ('faltas3', models.CharField(max_length=4)),
                ('faltas4', models.CharField(max_length=4)),
                ('faltas', models.CharField(max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, null=True)),
                ('ibge', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('uf', models.CharField(max_length=2)),
                ('ibge', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=10)),
                ('parcela', models.CharField(max_length=5)),
                ('cota', models.CharField(max_length=5)),
                ('historico', models.TextField()),
                ('dtemissao', models.CharField(max_length=10)),
                ('vlr_titulo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('dtbaixa', models.CharField(max_length=10)),
                ('vlr_baixa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('vlr_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('vlr_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ImportacaoCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_importacao', models.CharField(max_length=100)),
                ('observacao', models.TextField()),
                ('dtupload', models.DateField()),
                ('stimportacao', models.BooleanField(default=False)),
                ('dtimportacao', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(upload_to='csv')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('razaosocial', models.CharField(max_length=100, null=True)),
                ('nomefantasia', models.CharField(max_length=100)),
                ('cgc', models.CharField(max_length=20)),
                ('inscestadual', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('telefax', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=10)),
                ('contato', models.CharField(max_length=40)),
                ('imagem', models.ImageField(blank=True, default='instituicao/sem_foto.png', null=True, upload_to='instituicao')),
                ('dtcadastro', models.DateField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('dtmensagem', models.DateField()),
                ('descricao', models.TextField()),
                ('stmensagem', models.BooleanField()),
                ('usuario', models.ManyToManyField(related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do Pa\xeds')),
                ('abreviacao', models.CharField(max_length=3, verbose_name='Abrevia\xe7\xe3o do Pa\xeds')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
                ('diasletivos', models.IntegerField()),
                ('dtinicial', models.DateField()),
                ('dtfinal', models.DateField(blank=True, null=True)),
                ('calendario', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('registro_professor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('nome_abreviado', models.CharField(max_length=40)),
                ('dtnascimento', models.DateField()),
                ('sexo', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=20)),
                ('identidade', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('endereco', models.CharField(max_length=140)),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=3)),
                ('cep', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.ImageField(blank=True, default='professores/sem_foto.png', null=True, upload_to='professores')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('registro_responsavel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('nome_abreviado', models.CharField(max_length=40)),
                ('dtnascimento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=20)),
                ('identidade', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('endereco', models.CharField(max_length=140)),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=3)),
                ('cep', models.CharField(max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.ImageField(blank=True, default='responsavel/sem_foto.png', null=True, upload_to='responsavel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaImportacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='importacaocsv',
            name='tabelaimportacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.TabelaImportacao'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='periodoletivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Responsavel'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Pais'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Pais'),
        ),
        migrations.AddField(
            model_name='boletim',
            name='periodoletivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Responsavel'),
        ),
    ]
