# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_nome', models.CharField(max_length=60, null=True)),
                ('cidade_ibge', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_nome', models.CharField(max_length=40)),
                ('estado_uf', models.CharField(max_length=2)),
                ('estado_ibge', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_nome', models.CharField(max_length=40, verbose_name='Nome do Pa\xeds')),
                ('pais_abreviacao', models.CharField(max_length=3, verbose_name='Abrevia\xe7\xe3o do Pa\xeds')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Pais'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Pais'),
        ),
    ]
