# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemusuarios',
            name='usuarios',
        ),
        migrations.DeleteModel(
            name='ImagemUsuarios',
        ),
    ]
