# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='telefone',
            new_name='celular',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='arquivo_importado',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='dtnascimento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='identidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone2',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='aluno',
            name='whatsapp',
            field=models.CharField(default=99, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boletim',
            name='faltas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boletim',
            name='notas',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
