# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do Pa\xeds')),
                ('abreviacao', models.CharField(max_length=3, verbose_name='Abrevia\xe7\xe3o do Pa\xeds')),
                ('stativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='codigo',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Pais'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Pais'),
            preserve_default=False,
        ),
    ]
