# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='faltas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='boletim',
            name='notas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
