# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, null=True)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cgc', models.CharField(max_length=20)),
                ('insc_estadual', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('telefax', models.CharField(max_length=15)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Estado')),
            ],
        ),
    ]
