# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-19 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='usuario',
        ),
    ]
