# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180314_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('turno', models.CharField(max_length=30)),
                ('turma', models.CharField(max_length=30)),
                ('disciplina', models.CharField(max_length=50)),
                ('notas1', models.CharField(max_length=10)),
                ('notas2', models.CharField(max_length=10)),
                ('notas3', models.CharField(max_length=10)),
                ('notas4', models.CharField(max_length=10)),
                ('media', models.CharField(max_length=10)),
                ('recuperacao', models.CharField(max_length=10)),
                ('faltas1', models.CharField(max_length=4)),
                ('faltas2', models.CharField(max_length=4)),
                ('faltas3', models.CharField(max_length=4)),
                ('faltas4', models.CharField(max_length=4)),
                ('faltas', models.CharField(max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
                ('periodoletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo')),
            ],
        ),
    ]
