# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190125_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('registro_responsavel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.ImageField(blank=True, default='responsavel/sem_foto.png', null=True, upload_to='responsavel')),
                ('arquivo_importado', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, default='alunos/sem_foto.png', null=True, upload_to='alunos'),
        ),
    ]
