# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_responsavel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='nome_disciplina',
            field=models.CharField(default=99, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boletim',
            name='disciplina',
            field=models.CharField(max_length=10),
        ),
    ]
