# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-31 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180831_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='faltas',
            field=models.IntegerField(),
        ),
    ]
