# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-26 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180426_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
