# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171114_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cadastro', models.DateField(auto_created=True)),
                ('razao_social', models.CharField(max_length=100, null=True)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cgc', models.CharField(max_length=20)),
                ('insc_estadual', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('telefax', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=9)),
                ('contato', models.CharField(max_length=40)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagem')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Estado')),
            ],
        ),
    ]
