# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-28 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190128_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
