# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_boletim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletim',
            old_name='media',
            new_name='campo',
        ),
        migrations.RenameField(
            model_name='boletim',
            old_name='notas1',
            new_name='notas',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='faltas1',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='faltas2',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='faltas3',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='faltas4',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='notas2',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='notas3',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='notas4',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='recuperacao',
        ),
        migrations.AddField(
            model_name='boletim',
            name='etapa',
            field=models.CharField(default=99, max_length=60),
            preserve_default=False,
        ),
    ]
