# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_auto_20180305_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='usuario',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
