# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_instituicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='cidade_ibge',
            new_name='cod_ibge',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='cidade_nome',
            new_name='nome',
        ),
    ]
