# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180314_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletim',
            name='campo',
        ),
    ]
