# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_professor_arquivo_importado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='arquivo_importado',
            field=models.CharField(default=99, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletim',
            name='arquivo_importado',
            field=models.CharField(default=99, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeiro',
            name='arquivo_importado',
            field=models.CharField(default=99, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsavel',
            name='arquivo_importado',
            field=models.CharField(default=99, max_length=200),
            preserve_default=False,
        ),
    ]
