# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='telefone2',
            new_name='celular',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
