# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_boletim_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='numero_alunos',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
    ]
