# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_mensagem_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='usuario',
            field=models.ManyToManyField(related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
