# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20171114_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='cod_ibge',
            new_name='cd_ibge',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='nm_nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='sg_uf',
            new_name='uf',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='pais_abreviacao',
            new_name='abreviacao',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='pais_nome',
            new_name='nome',
        ),
    ]
