# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20171114_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='cd_ibge',
            new_name='ibge',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='cd_ibge',
            new_name='ibge',
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='dt_cadastro',
            new_name='dtcadastro',
        ),
    ]
