# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180427_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletim',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='periodoletivo',
        ),
        migrations.DeleteModel(
            name='Boletim',
        ),
    ]
