# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='portal.Responsavel'),
            preserve_default=False,
        ),
    ]
