# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180430_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('registro_boletim', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('turno', models.CharField(max_length=30)),
                ('turma', models.CharField(max_length=30)),
                ('disciplina', models.CharField(max_length=10)),
                ('nome_disciplina', models.CharField(max_length=50)),
                ('etapa', models.CharField(max_length=60)),
                ('notas', models.CharField(max_length=10)),
                ('faltas', models.CharField(max_length=4)),
                ('arquivo_importado', models.CharField(max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
                ('periodoletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo')),
            ],
        ),
    ]
