# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20171114_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('dtalerta', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('stmensagem', models.BooleanField()),
            ],
        ),
    ]
