# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='descricao',
            field=models.TextField(),
        ),
    ]
