# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20190131_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='identidade',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='telefone',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='dtnascimento',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='telefone2',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='uf',
        ),
        migrations.AlterField(
            model_name='professor',
            name='imagem',
            field=models.FileField(blank=True, default='alunos/sem_foto.png', null=True, upload_to='alunos'),
        ),
    ]
