# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20171114_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='insc_estadual',
            new_name='inscestadual',
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='nome_fantasia',
            new_name='nomefantasia',
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='razao_social',
            new_name='razaosocial',
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cep',
            field=models.CharField(max_length=10),
        ),
    ]
