# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-12 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0011_auto_20190212_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='imagem',
            field=models.FileField(blank=True, default='professores/sem_foto.png', null=True, upload_to='alunos'),
        ),
    ]
