# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20171116_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='dtcadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens'),
        ),
    ]
