# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20171116_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.FileField(upload_to=b''),
        ),
    ]
