# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-12 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0013_auto_20190212_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('usuario', models.ManyToManyField(related_name='tp_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
