# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20171116_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.CharField(max_length=250),
        ),
    ]
