# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-13 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_tipouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipouser',
            name='usuario',
        ),
    ]
