# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20171117_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='imagens'),
        ),
    ]
