# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20171117_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.ImageField(blank=True, default='media/imagens/sem_foto.jpg', null=True, upload_to='imagens'),
        ),
    ]
