# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-13 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0017_remove_professor_nome_abreviado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='responsavel',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
