# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_periodoletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
