# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20190213_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='arquivo_importado',
            field=models.CharField(default=99, max_length=200),
            preserve_default=False,
        ),
    ]
