# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20171121_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='inscestadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='telefax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
