# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-08 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_aluno_arquivo_importado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='usuario',
        ),
    ]
