# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20171121_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoletivo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='csv'),
        ),
    ]
