# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_remove_periodoletivo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoletivo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
