# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_importacaocsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaocsv',
            name='arquivo',
            field=models.FileField(upload_to='csv'),
        ),
    ]
