# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20171124_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaocsv',
            name='stimportacao',
            field=models.BooleanField(default=False),
        ),
    ]
