# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_importacaocsv_dtupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaocsv',
            name='dtupload',
            field=models.DateField(blank=True, null=True),
        ),
    ]
