# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20171127_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaocsv',
            name='dtimportacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacaocsv',
            name='dtupload',
            field=models.DateField(),
        ),
    ]
