# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20171129_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoletivo',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodoletivo',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
