# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_periodoletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoletivo',
            name='stopcao',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
