# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20171129_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='id',
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
