# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_disciplina_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='turma',
            field=models.ManyToManyField(blank=True, to='portal.Turma'),
        ),
    ]
