# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_auto_20171201_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turma',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Turma'),
            preserve_default=False,
        ),
    ]
