# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_auto_20171201_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turma',
        ),
    ]
