# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_remove_disciplina_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ManyToManyField(to='portal.Disciplina'),
        ),
    ]
