# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='registro_aluno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
