# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_auto_20171204_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='intituicao',
            new_name='instituicao',
        ),
    ]
