# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0056_auto_20171204_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaocsv',
            name='nomeimportacao',
            field=models.CharField(default=9999, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importacaocsv',
            name='observacao',
            field=models.TextField(default=9999),
            preserve_default=False,
        ),
    ]
