# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0058_auto_20171205_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codturma', models.CharField(max_length=20)),
                ('nometurma', models.CharField(max_length=80)),
                ('coddisciplina', models.CharField(max_length=20)),
                ('nomedisciplina', models.CharField(max_length=80)),
                ('disciplinaabreviado', models.CharField(max_length=30)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Instituicao')),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='instituicao',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
