# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0061_auto_20171206_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alunos'),
        ),
    ]
