# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0062_aluno_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmadisciplina',
            name='registro_aluno',
            field=models.ManyToManyField(to='portal.Aluno'),
        ),
    ]
