# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0063_turmadisciplina_registro_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmadisciplina',
            name='registro_aluno',
        ),
    ]
