# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0064_remove_turmadisciplina_registro_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmadisciplina',
            name='periodoletivo',
            field=models.ForeignKey(default=2017, on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo'),
            preserve_default=False,
        ),
    ]
