# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0065_turmadisciplina_periodoletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmadisciplina',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno'),
            preserve_default=False,
        ),
    ]
