# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0067_auto_20171207_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmadisciplina',
            name='aluno',
        ),
    ]
