# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0074_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='periodoletivo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='turmadisciplina',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
