# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0076_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmadisciplina',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
