# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0079_auto_20171227_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notasfalta',
            old_name='notasfalta',
            new_name='faltas',
        ),
        migrations.RemoveField(
            model_name='notasfalta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notasfalta',
            name='notas',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
