# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0080_auto_20171227_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotasFalta',
            new_name='Boletim',
        ),
    ]
