# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0082_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='abreviacao',
            field=models.CharField(default=999, max_length=30),
            preserve_default=False,
        ),
    ]
