# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-04 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0086_auto_20180104_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ManyToManyField(to='portal.Turma'),
        ),
    ]
