# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0087_disciplina_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='turma',
            new_name='turmas',
        ),
    ]
