# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0088_auto_20180105_1715'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='disciplina',
    #         name='turmas',
    #         field=models.ManyToManyField(related_name='disciplinas', to='portal.Turma'),
    #     ),
    # ]
