# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0089_auto_20180110_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turmas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turmas',
            field=models.ForeignKey(default=888, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='portal.Turma'),
            preserve_default=False,
        ),
        # migrations.AlterModelTable(
        #     name='disciplina',
        #     table='Disciplina',
        # ),
    ]
