# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0094_auto_20180110_1248'),
        ('portal', '0093_auto_20180110_1246'),
    ]

    operations = [
    ]
