# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180110_1619'),
        ('portal', '0097_auto_20180110_1253'),
    ]

    operations = [
    ]
