# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0098_merge_20180110_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacaocsv',
            name='tabelaimportacao',
        ),
    ]
