# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0099_remove_importacaocsv_tabelaimportacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaocsv',
            name='tabelaimportacao',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='portal.TabelaImportacao'),
            preserve_default=False,
        ),
    ]
