# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0101_remove_disciplina_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='turmas',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='portal.Turma'),
            preserve_default=False,
        ),
    ]
