# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0102_disciplina_turmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turmas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turmas',
            field=models.ManyToManyField(related_name='disciplinas', to='portal.Turma'),
        ),
    ]
