# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0104_remove_disciplina_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ManyToManyField(to='portal.Disciplina'),
        ),
    ]
