# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0106_auto_20180111_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='disciplina',
            new_name='disciplinas',
        ),
    ]
