# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0110_pais_tipo_pais'),
        ('portal', '0109_auto_20180112_0925'),
    ]

    operations = [
    ]
