# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0111_merge_20180112_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='tipo_pais',
        ),
    ]
