# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0115_boletim'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasFaltas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Instituicao')),
                ('periodoletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo')),
            ],
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='periodoletivo',
        ),
        migrations.DeleteModel(
            name='Boletim',
        ),
    ]
