# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0126_auto_20180116_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(related_name='alunos', to='portal.Aluno'),
        ),
    ]
