# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0127_disciplina_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='alunos',
        ),
    ]
