# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 16:22
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0130_remove_turma_alunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Disciplina')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Instituicao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Turma')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='matricula',
            field=models.ManyToManyField(through='portal.Boletim', to='portal.Aluno'),
        ),
    ]
