# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0131_auto_20180116_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='faltas',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
