# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0132_boletim_faltas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletim',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='matricula',
        ),
        migrations.DeleteModel(
            name='Boletim',
        ),
    ]
