# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0135_boletim_periodoletivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='faltas',
            field=models.IntegerField(),
        ),
    ]
