# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0137_auto_20180116_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Instituicao')),
                ('periodoletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Turma')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='matriculas',
            field=models.ManyToManyField(through='portal.Matricula', to='portal.Aluno'),
        ),
    ]
