# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0138_auto_20180116_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turmas',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='periodoletivo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='matriculas',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
