# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0139_auto_20180117_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodoletivo',
            name='instituicao',
        ),
    ]
