# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0140_remove_periodoletivo_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='instituicao',
        ),
    ]
