# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0142_remove_aluno_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacaocsv',
            name='instituicao',
        ),
    ]
