# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 19:31
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0144_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('turno', models.CharField(max_length=30)),
                ('turma', models.CharField(max_length=30)),
                ('disciplina', models.CharField(max_length=50)),
                ('etapa', models.CharField(max_length=60)),
                ('notas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('faltas', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
                ('periodoletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PeriodoLetivo')),
            ],
        ),
    ]
