# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0147_boletim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.ImageField(blank=True, default='media/instituicao/sem_foto.jpg', null=True, upload_to='imagens'),
        ),
    ]
