# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-19 17:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('portal', '0148_auto_20180119_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemUsuarios',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imagem', models.ImageField(blank=True, default='media/usuarios/sem_foto.jpg', null=True, upload_to='usuarios')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
