# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-19 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0150_auto_20180119_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='media/usuarios/sem_foto.jpg', null=True, upload_to='usuarios')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
