# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0151_imagemusuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('registro_responsavel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('nome_abreviado', models.CharField(max_length=40)),
                ('dtnascimento', models.DateField()),
                ('sexo', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=20)),
                ('identidade', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('endereco', models.CharField(max_length=140)),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone2', models.CharField(max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='alunos')),
                ('aluno', models.ManyToManyField(related_name='aluno', to='portal.Aluno')),
            ],
        ),
    ]
