# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0152_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, default='media/professores/sem_foto.jpg', null=True, upload_to='professores'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='imagem',
            field=models.ImageField(blank=True, default='media/usuarios/sem_foto.jpg', null=True, upload_to='responsavel'),
        ),
    ]
