# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0153_auto_20180123_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='imagemusuarios',
            name='imagem',
            field=models.ImageField(blank=True, default='usuarios/sem_foto.jpg', null=True, upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.ImageField(blank=True, default='/instituicao/sem_foto.jpg', null=True, upload_to='imagens'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, default='professores/sem_foto.jpg', null=True, upload_to='professores'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='imagem',
            field=models.ImageField(blank=True, default='responsavel/sem_foto.png', null=True, upload_to='responsavel'),
        ),
    ]
