# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0154_auto_20180124_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='aluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='portal.Responsavel'),
            preserve_default=False,
        ),
    ]
