# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0155_auto_20180124_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, default='alunos/sem_foto.png', null=True, upload_to='alunos'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf',
            field=models.CharField(max_length=3),
        ),
    ]
