# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0156_auto_20180124_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='professor',
            name='uf',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='uf',
            field=models.CharField(max_length=3),
        ),
    ]
