# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 12:41
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0158_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='vlr_baixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='vlr_desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='vlr_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
