# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0159_auto_20180129_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='ibge',
            new_name='estado_ibge',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='nome',
            new_name='estado_nome',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='uf',
            new_name='estado_uf',
        ),
    ]
