# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0160_auto_20180205_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estado_ibge',
            new_name='ibge',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='estado_nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='estado_uf',
            new_name='uf',
        ),
    ]
