# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0163_auto_20180205_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
